const axios = require('axios');
const partitionController = {};

partitionController.totalPartitionCount = async (req, res, next) => {
  try {
    (`http://localhost:${port}/api/v1/query?query=kafka_controller_kafkacontroller_globalpartitioncount`)
  }
}

partitionController.offlinePartitionCount = async (req, res, next) => {
    
}

partitionController.underReplicated = async (req, res, next) => {
  try {
    const { port } = res.locals;
    const { data: { data: { result } } } = await axios.get(`http://localhost:${port}/api/v1/query?query=kafka_cluster_partition_underreplicated`);
    res.locals.totalPartitionCount = result;
    return next();
  } catch (err) {
    return next(err);
  }
  /**
   * "result":[
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"0",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"0",
               "topic":"test"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"0",
               "topic":"topic1"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"0",
               "topic":"topic2"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"0",
               "topic":"topic3"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"0",
               "topic":"topic4"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"1",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"1",
               "topic":"topic1"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"1",
               "topic":"topic2"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"1",
               "topic":"topic3"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"1",
               "topic":"topic4"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"10",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"11",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"12",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"13",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"14",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"15",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"16",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"17",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"18",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"19",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"2",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"20",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"21",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"22",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"23",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"24",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"25",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"26",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"27",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"28",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"29",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"3",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"30",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"31",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"32",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"33",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"34",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"35",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"36",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"37",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"38",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"39",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"4",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"40",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"41",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"42",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"43",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"44",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"45",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"46",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"47",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"48",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"49",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"5",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"6",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"7",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"8",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         },
         {
            "metric":{
               "__name__":"kafka_cluster_partition_underreplicated",
               "instance":"kafka:7071",
               "job":"kafka",
               "partition":"9",
               "topic":"__consumer_offsets"
            },
            "value":[
               1646358635.392,
               "0"
            ]
         }
      ]
   */
}


module.exports = partitionController;